# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: M30XY_control
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_M30XY_control main.cpp)
target_link_libraries(Example_M30XY_control PRIVATE DegorasKinesis)

# **********************************************************************************************************************
