# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: M30X_control
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_M30X_control main.cpp)
target_link_libraries(Example_M30X_control PRIVATE LibDegorasKinesis)

# **********************************************************************************************************************
