# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: multi_device_control
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_multi_device_control main.cpp)
target_link_libraries(Example_multi_device_control PRIVATE LibDegorasKinesis)

# **********************************************************************************************************************
