# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: m30x
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_m30x main.cpp)
target_link_libraries(Example_m30x PRIVATE LibDegorasKinesis)

# **********************************************************************************************************************
