# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: basic_device_connection
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_basic_device_connection main.cpp)
target_link_libraries(Example_basic_device_connection PRIVATE DegorasKinesis)

# **********************************************************************************************************************
