# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: K10CR2_control
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_K10CR2_control main.cpp)
target_link_libraries(Example_K10CR2_control PRIVATE LibDegorasKinesis)

# **********************************************************************************************************************
