/*
 *      Copyright(C) Milethos Technologies SLU. 2025
 *      All rights reserved. Reproduction in whole or in
 *      part is prohibited without the written consent of
 *      the copyright holder.
 */

#pragma once

// C++ INCLUDES
#include <mutex>
#include <random>
#include <set>

// LEOBASE INCLUDES
#include "LeoBase/Aliases/Global"
#include "LeoBase/Crypto/leo_uuid.h"

// LEOBASE MACROS
LEOBASE_MODULE_BEGIN(crypto)

// ---------------------------------------------------------------------------------------------------------------------

/**
 * @class LeoUUIDGenerator
 *
 * @brief This singleton class provides functionality for generating UUID (Universally Unique Identifier).
 *
 * This singleton class supports generation of Version 4 UUIDs as per RFC 4122. A Version 4 UUID is randomly generated.
 *
 * The UUID generated by this class is a 128-bit value. The string representation is a series of lowercase hexadecimal
 * digits in groups, separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 alphanumeric
 * characters and four hyphens).
 *
 * The algorithm used for generation is as follows:
 * 1. Generate 16 random bytes
 * 2. Adjust certain bits according to RFC 4122 section 4.4 as follows:
 *    a. Set the four most significant bits of the 7th byte to 0100'B, so the high nibble is "4".
 *    b. Set the two most significant bits of the 9th byte to 10'B, so the high nibble will be one of "8", "9",
 *    "A", or "B".
 * 3. Convert the byte array to a string in the form of 8-4-4-4-12
 *
 * @warning This class relies on std::random_device for random number generation. On some platforms, this does not
 * actually provide a non-deterministic random number generator. In such cases, the randomness of the generated UUIDs
 * may be weaker and a random seed will be generated using a timestamp.
 */
class LEOBASE_EXPORT LeoUUIDGenerator
{
public:

    /**
     * @brief Access to the singleton instance
     */
    static LeoUUIDGenerator& getInstance();

    /**
     * @brief Generates a version 4 UUID
     * @return A unique UUID
     */
    static LeoUUID generateUUIDv4();

    // Deleted constructors and assignment operators.
    LeoUUIDGenerator(const LeoUUIDGenerator &) = delete;
    LeoUUIDGenerator(LeoUUIDGenerator&&) = delete;
    LeoUUIDGenerator& operator=(const LeoUUIDGenerator &) = delete;
    LeoUUIDGenerator& operator=(LeoUUIDGenerator&&) = delete;

private:

    // Private generator.
    LeoUUID generateUUIDv4Private();

    // Private constructor.
    LeoUUIDGenerator();

    // Members.
    std::random_device rd_;             ///< Random device.
    std::mt19937_64 gen_;               ///< Generator.
};

// ---------------------------------------------------------------------------------------------------------------------

LEOBASE_MODULE_END
