# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: m30xy
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_m30xy main.cpp)
target_link_libraries(Example_m30xy PRIVATE LibDegorasKinesis)

# **********************************************************************************************************************
