# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: basic_device_discovery
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_basic_device_discovery main.cpp)
target_link_libraries(Example_basic_device_discovery PRIVATE DegorasKinesis)

# **********************************************************************************************************************
